/**
 * Even Fibonacci numbers
 * Each new term in the Fibonacci sequence is generated by 
 * adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose
 * values do not exceed four million, find the sum of the even-valued terms.
 */

#include <iostream>

/* Declaration of functions */
long long fibonacci();

int main()
{
    long long result = fibonacci();

    std::cout << result << std::endl;

    return 0;
}

/**
 * Find the sum of the even-valued terms
 */
long long fibonacci()
{
    long long fib1 = 0;
    long long fib2 = 1;
    long long fib3 = 1;
    long long even_sum = 0;

    while (fib1 < 4000000)
    {
        fib1 = fib2 + fib3;
        fib2 = fib3;
        fib3 = fib1;
        if (fib1 % 2 == 0)
        {
            even_sum += fib1;
        }
    }
    return even_sum;
}
